/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheTrailRouteImport } from './routes/the-trail'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as SitesSlugRouteImport } from './routes/sites/$slug'
import { Route as ChaptersTheStateRouteImport } from './routes/chapters/the-state'
import { Route as ChaptersTheRoadRouteImport } from './routes/chapters/the-road'
import { Route as ChaptersTheRiverRouteImport } from './routes/chapters/the-river'
import { Route as ChaptersTheMarchRouteImport } from './routes/chapters/the-march'
import { Route as ChaptersTheAgreementRouteImport } from './routes/chapters/the-agreement'

const TheTrailRoute = TheTrailRouteImport.update({
  id: '/the-trail',
  path: '/the-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSlugRoute = SitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheStateRoute = ChaptersTheStateRouteImport.update({
  id: '/chapters/the-state',
  path: '/chapters/the-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheRoadRoute = ChaptersTheRoadRouteImport.update({
  id: '/chapters/the-road',
  path: '/chapters/the-road',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheRiverRoute = ChaptersTheRiverRouteImport.update({
  id: '/chapters/the-river',
  path: '/chapters/the-river',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheMarchRoute = ChaptersTheMarchRouteImport.update({
  id: '/chapters/the-march',
  path: '/chapters/the-march',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheAgreementRoute = ChaptersTheAgreementRouteImport.update({
  id: '/chapters/the-agreement',
  path: '/chapters/the-agreement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/stories': typeof StoriesRoute
  '/the-trail': typeof TheTrailRoute
  '/chapters/the-agreement': typeof ChaptersTheAgreementRoute
  '/chapters/the-march': typeof ChaptersTheMarchRoute
  '/chapters/the-river': typeof ChaptersTheRiverRoute
  '/chapters/the-road': typeof ChaptersTheRoadRoute
  '/chapters/the-state': typeof ChaptersTheStateRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/stories': typeof StoriesRoute
  '/the-trail': typeof TheTrailRoute
  '/chapters/the-agreement': typeof ChaptersTheAgreementRoute
  '/chapters/the-march': typeof ChaptersTheMarchRoute
  '/chapters/the-river': typeof ChaptersTheRiverRoute
  '/chapters/the-road': typeof ChaptersTheRoadRoute
  '/chapters/the-state': typeof ChaptersTheStateRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/sites': typeof SitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/stories': typeof StoriesRoute
  '/the-trail': typeof TheTrailRoute
  '/chapters/the-agreement': typeof ChaptersTheAgreementRoute
  '/chapters/the-march': typeof ChaptersTheMarchRoute
  '/chapters/the-river': typeof ChaptersTheRiverRoute
  '/chapters/the-road': typeof ChaptersTheRoadRoute
  '/chapters/the-state': typeof ChaptersTheStateRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/stories'
    | '/the-trail'
    | '/chapters/the-agreement'
    | '/chapters/the-march'
    | '/chapters/the-river'
    | '/chapters/the-road'
    | '/chapters/the-state'
    | '/sites/$slug'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/stories'
    | '/the-trail'
    | '/chapters/the-agreement'
    | '/chapters/the-march'
    | '/chapters/the-river'
    | '/chapters/the-road'
    | '/chapters/the-state'
    | '/sites/$slug'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/stories'
    | '/the-trail'
    | '/chapters/the-agreement'
    | '/chapters/the-march'
    | '/chapters/the-river'
    | '/chapters/the-road'
    | '/chapters/the-state'
    | '/sites/$slug'
    | '/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  StoriesRoute: typeof StoriesRoute
  TheTrailRoute: typeof TheTrailRoute
  ChaptersTheAgreementRoute: typeof ChaptersTheAgreementRoute
  ChaptersTheMarchRoute: typeof ChaptersTheMarchRoute
  ChaptersTheRiverRoute: typeof ChaptersTheRiverRoute
  ChaptersTheRoadRoute: typeof ChaptersTheRoadRoute
  ChaptersTheStateRoute: typeof ChaptersTheStateRoute
  SitesSlugRoute: typeof SitesSlugRoute
  SitesIndexRoute: typeof SitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-trail': {
      id: '/the-trail'
      path: '/the-trail'
      fullPath: '/the-trail'
      preLoaderRoute: typeof TheTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$slug': {
      id: '/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof SitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-state': {
      id: '/chapters/the-state'
      path: '/chapters/the-state'
      fullPath: '/chapters/the-state'
      preLoaderRoute: typeof ChaptersTheStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-road': {
      id: '/chapters/the-road'
      path: '/chapters/the-road'
      fullPath: '/chapters/the-road'
      preLoaderRoute: typeof ChaptersTheRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-river': {
      id: '/chapters/the-river'
      path: '/chapters/the-river'
      fullPath: '/chapters/the-river'
      preLoaderRoute: typeof ChaptersTheRiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-march': {
      id: '/chapters/the-march'
      path: '/chapters/the-march'
      fullPath: '/chapters/the-march'
      preLoaderRoute: typeof ChaptersTheMarchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-agreement': {
      id: '/chapters/the-agreement'
      path: '/chapters/the-agreement'
      fullPath: '/chapters/the-agreement'
      preLoaderRoute: typeof ChaptersTheAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  StoriesRoute: StoriesRoute,
  TheTrailRoute: TheTrailRoute,
  ChaptersTheAgreementRoute: ChaptersTheAgreementRoute,
  ChaptersTheMarchRoute: ChaptersTheMarchRoute,
  ChaptersTheRiverRoute: ChaptersTheRiverRoute,
  ChaptersTheRoadRoute: ChaptersTheRoadRoute,
  ChaptersTheStateRoute: ChaptersTheStateRoute,
  SitesSlugRoute: SitesSlugRoute,
  SitesIndexRoute: SitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
