/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheTrailRouteImport } from './routes/the-trail'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as SitesSlugRouteImport } from './routes/sites/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as ChaptersTheSoundRouteImport } from './routes/chapters/the-sound'
import { Route as ChaptersTheSessionsRouteImport } from './routes/chapters/the-sessions'
import { Route as ChaptersTheRailroadRouteImport } from './routes/chapters/the-railroad'
import { Route as ChaptersTheNextGenerationRouteImport } from './routes/chapters/the-next-generation'
import { Route as ChaptersTheFestivalRouteImport } from './routes/chapters/the-festival'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'

const TheTrailRoute = TheTrailRouteImport.update({
  id: '/the-trail',
  path: '/the-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSlugRoute = SitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheSoundRoute = ChaptersTheSoundRouteImport.update({
  id: '/chapters/the-sound',
  path: '/chapters/the-sound',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheSessionsRoute = ChaptersTheSessionsRouteImport.update({
  id: '/chapters/the-sessions',
  path: '/chapters/the-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheRailroadRoute = ChaptersTheRailroadRouteImport.update({
  id: '/chapters/the-railroad',
  path: '/chapters/the-railroad',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersTheNextGenerationRoute =
  ChaptersTheNextGenerationRouteImport.update({
    id: '/chapters/the-next-generation',
    path: '/chapters/the-next-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChaptersTheFestivalRoute = ChaptersTheFestivalRouteImport.update({
  id: '/chapters/the-festival',
  path: '/chapters/the-festival',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/stories': typeof StoriesRoute
  '/the-trail': typeof TheTrailRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/chapters/the-festival': typeof ChaptersTheFestivalRoute
  '/chapters/the-next-generation': typeof ChaptersTheNextGenerationRoute
  '/chapters/the-railroad': typeof ChaptersTheRailroadRoute
  '/chapters/the-sessions': typeof ChaptersTheSessionsRoute
  '/chapters/the-sound': typeof ChaptersTheSoundRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/stories': typeof StoriesRoute
  '/the-trail': typeof TheTrailRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/chapters/the-festival': typeof ChaptersTheFestivalRoute
  '/chapters/the-next-generation': typeof ChaptersTheNextGenerationRoute
  '/chapters/the-railroad': typeof ChaptersTheRailroadRoute
  '/chapters/the-sessions': typeof ChaptersTheSessionsRoute
  '/chapters/the-sound': typeof ChaptersTheSoundRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/sites': typeof SitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/stories': typeof StoriesRoute
  '/the-trail': typeof TheTrailRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/chapters/the-festival': typeof ChaptersTheFestivalRoute
  '/chapters/the-next-generation': typeof ChaptersTheNextGenerationRoute
  '/chapters/the-railroad': typeof ChaptersTheRailroadRoute
  '/chapters/the-sessions': typeof ChaptersTheSessionsRoute
  '/chapters/the-sound': typeof ChaptersTheSoundRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/stories'
    | '/the-trail'
    | '/api/subscribe'
    | '/chapters/the-festival'
    | '/chapters/the-next-generation'
    | '/chapters/the-railroad'
    | '/chapters/the-sessions'
    | '/chapters/the-sound'
    | '/guides/$slug'
    | '/sites/$slug'
    | '/guides/'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/stories'
    | '/the-trail'
    | '/api/subscribe'
    | '/chapters/the-festival'
    | '/chapters/the-next-generation'
    | '/chapters/the-railroad'
    | '/chapters/the-sessions'
    | '/chapters/the-sound'
    | '/guides/$slug'
    | '/sites/$slug'
    | '/guides'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/stories'
    | '/the-trail'
    | '/api/subscribe'
    | '/chapters/the-festival'
    | '/chapters/the-next-generation'
    | '/chapters/the-railroad'
    | '/chapters/the-sessions'
    | '/chapters/the-sound'
    | '/guides/$slug'
    | '/sites/$slug'
    | '/guides/'
    | '/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  StoriesRoute: typeof StoriesRoute
  TheTrailRoute: typeof TheTrailRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ChaptersTheFestivalRoute: typeof ChaptersTheFestivalRoute
  ChaptersTheNextGenerationRoute: typeof ChaptersTheNextGenerationRoute
  ChaptersTheRailroadRoute: typeof ChaptersTheRailroadRoute
  ChaptersTheSessionsRoute: typeof ChaptersTheSessionsRoute
  ChaptersTheSoundRoute: typeof ChaptersTheSoundRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  SitesSlugRoute: typeof SitesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  SitesIndexRoute: typeof SitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-trail': {
      id: '/the-trail'
      path: '/the-trail'
      fullPath: '/the-trail'
      preLoaderRoute: typeof TheTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$slug': {
      id: '/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof SitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-sound': {
      id: '/chapters/the-sound'
      path: '/chapters/the-sound'
      fullPath: '/chapters/the-sound'
      preLoaderRoute: typeof ChaptersTheSoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-sessions': {
      id: '/chapters/the-sessions'
      path: '/chapters/the-sessions'
      fullPath: '/chapters/the-sessions'
      preLoaderRoute: typeof ChaptersTheSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-railroad': {
      id: '/chapters/the-railroad'
      path: '/chapters/the-railroad'
      fullPath: '/chapters/the-railroad'
      preLoaderRoute: typeof ChaptersTheRailroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-next-generation': {
      id: '/chapters/the-next-generation'
      path: '/chapters/the-next-generation'
      fullPath: '/chapters/the-next-generation'
      preLoaderRoute: typeof ChaptersTheNextGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/the-festival': {
      id: '/chapters/the-festival'
      path: '/chapters/the-festival'
      fullPath: '/chapters/the-festival'
      preLoaderRoute: typeof ChaptersTheFestivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  StoriesRoute: StoriesRoute,
  TheTrailRoute: TheTrailRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ChaptersTheFestivalRoute: ChaptersTheFestivalRoute,
  ChaptersTheNextGenerationRoute: ChaptersTheNextGenerationRoute,
  ChaptersTheRailroadRoute: ChaptersTheRailroadRoute,
  ChaptersTheSessionsRoute: ChaptersTheSessionsRoute,
  ChaptersTheSoundRoute: ChaptersTheSoundRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  SitesSlugRoute: SitesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  SitesIndexRoute: SitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
